name: CI Pipeline

on:
  schedule:
    # Executa nos dias úteis às 9h, 12h, 15h e 18h (UTC)
    - cron: "0 12,15,18,21 * * 1-5"  # Brasil (UTC-3)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies and build
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn -Dtest=runner.CucumberTest test
